# Site settings
title: "Jennings_Wang"
keywords: "PHPer, Linux, Gentoo,  Mac OSX, Computer Security"
description: "Hobbies, Knowledge Records。"
baseurl: ""
url: "http://blog.sec0day.com"
highlighter: pygments
paginate: 5
author:
    name: Jennings_Wang
    github: hilllinux
    email:
    gitcafe: 
    twitter:
    facebook:
    googleplus:
    weibo: hilllinux
qiniudn: 
atom_path: /atom.xml
rss_path:  /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

# comment
comments:
    duoshuo:
        name: hilllinux
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid:       # 百度统计 js 代码后的字符串

# blogroll
blogroll: true
brlist:
    - text: "Jennings_wang"
      url : //blog.sec0day.com/
  #    - text: "刘静的博客"
  #      url : //upliu.net/
  #    - text: "小天地，大世界"
  #      url : //www.lyblog.net/
  #    - text: "清风的网络空间"
  #      url : //phpcj.org/
